id: P24A9A109
initial_creation_type: input
source_metadata:
  title: Dependent Origination
  language: fr
  description: 'Texts on the subject of dependent origination (pratītyasamutpāda;
    rten cing ''brel bar ''byung ba) or interdependent arising:'
  volume:
    20fb8c82f81d48ac9dad0d1492bc75dc:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    2778e92be6684b219bb7b78bad2e17c1:
      title: Commentary on Nāgārjuna's Verses on the Essence of Dependent Origination
      parent: Twelve Links
    6a40b8d0beff4c28819193f61d220d56:
      title: Commentary on the Noble Essence of the Dharmadhātu
      parent: Twelve Links
    f05d4bc5042c4f6db84a1f9c15806ef6:
      title: Verses on the Heart of Dependent Origination
      parent: Twelve Links
created_at: '2022-03-01T03:23:59.263423'
last_modified_at: '2022-03-01T03:23:59.263426'
